apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{/* See _configmap.tpl for the templates */}}
  server.conf: |
    {{- include "spire-server.config-main-template" . | fromYaml | toPrettyJson | nindent 4}}
